services:
  bitwarden:
    container_name: "bitwarden"
    depends_on:
      - "traefik"
    environment:
      INVITATIONS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
#      SIGNUPS_ALLOWED: "true"
      SIGNUPS_ALLOWED: "false"
      WEBSOCKET_ENABLED: "true"
    image: "vaultwarden/server:alpine"
    labels:
      # container auto-update
      com.centurylinklabs.watchtower.enable: true
      # traefik
      traefik.enable: true
      # bitwarden_rs
      traefik.http.routers.bitwarden.rule: "Host(`bw.${DOMAIN}`)"
      traefik.http.routers.bitwarden.service: "bitwarden"
      traefik.http.services.bitwarden.loadbalancer.server.port: 80
      # bitwarden_rs websocket
      traefik.http.routers.bitwarden-ws.rule: "Host(`bw.${DOMAIN}`) && Path(`/notifications/hub`)"
      traefik.http.middlewares.bitwarden-ws-strip.stripprefix.prefixes: "/notifications/hub"
      traefik.http.routers.bitwarden-ws.middlewares: "bitwarden-ws-strip"
      traefik.http.routers.bitwarden-ws.service: "bitwarden-ws"
      traefik.http.services.bitwarden-ws.loadbalancer.server.port: 3012
    networks:
      - "external"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "./bitwarden/data:/data"