accessLog: {}

api:
  dashboard: true

pilot:
  dashboard: false

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: "http"
      email: "${EMAIL}"
      storage: "acme.json"
      dnschallenge:
        provider: "cloudflare"
        delayBeforeCheck: 0

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          permanent: true
  https:
    address: ":443"
    http:
      middlewares:
        - security@file
      tls:
        certResolver: "letsencrypt"
        domains:
          - main: "${DOMAIN}"
            sans:
              - "*.${DOMAIN}"

global:
  sendAnonymousUsage: false

log:
  level: "ERROR"

providers:
  docker:
    endpoint: "tcp://docker_proxy:2375"
    exposedByDefault: false
    network: "traefik"
  file:
    directory: "/dynamic"
    watch: true
